/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArmingRouteImport } from './routes/arming'
import { Route as BlackboxRouteImport } from './routes/blackbox'
import { Route as CoderRouteImport } from './routes/coder'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as TelemetryRouteImport } from './routes/telemetry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmingRoute = ArmingRouteImport.update({
  id: '/arming',
  path: '/arming',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackboxRoute = BlackboxRouteImport.update({
  id: '/blackbox',
  path: '/blackbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CoderRoute = CoderRouteImport.update({
  id: '/coder',
  path: '/coder',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arming': typeof ArmingRoute
  '/blackbox': typeof BlackboxRoute
  '/coder': typeof CoderRoute
  '/drift': typeof DriftRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arming': typeof ArmingRoute
  '/blackbox': typeof BlackboxRoute
  '/coder': typeof CoderRoute
  '/drift': typeof DriftRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arming': typeof ArmingRoute
  '/blackbox': typeof BlackboxRoute
  '/coder': typeof CoderRoute
  '/drift': typeof DriftRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arming' | '/blackbox' | '/coder' | '/drift' | '/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arming' | '/blackbox' | '/coder' | '/drift' | '/telemetry'
  id:
    | '__root__'
    | '/'
    | '/arming'
    | '/blackbox'
    | '/coder'
    | '/drift'
    | '/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArmingRoute: typeof ArmingRoute
  BlackboxRoute: typeof BlackboxRoute
  CoderRoute: typeof CoderRoute
  DriftRoute: typeof DriftRoute
  TelemetryRoute: typeof TelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arming': {
      id: '/arming'
      path: '/arming'
      fullPath: '/arming'
      preLoaderRoute: typeof ArmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blackbox': {
      id: '/blackbox'
      path: '/blackbox'
      fullPath: '/blackbox'
      preLoaderRoute: typeof BlackboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coder': {
      id: '/coder'
      path: '/coder'
      fullPath: '/coder'
      preLoaderRoute: typeof CoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArmingRoute: ArmingRoute,
  BlackboxRoute: BlackboxRoute,
  CoderRoute: CoderRoute,
  DriftRoute: DriftRoute,
  TelemetryRoute: TelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
